wandb_version: 1

data_dir:
  desc: null
  value: /workspace/jordan/Span-Selection/download//conll
model_type:
  desc: null
  value: roberta
model_name_or_path:
  desc: null
  value: roberta-base
output_dir:
  desc: null
  value: /workspace/jordan/Span-Selection/outputs//conll/roberta-base-lr1e-5-epoch40-warmup800-bsz32-bepoch1-seed4
log_file:
  desc: null
  value: /workspace/jordan/Span-Selection/outputs//conll/roberta-base-lr1e-5-epoch40-warmup800-bsz32-bepoch1-seed4/train.log
task:
  desc: null
  value: conll
labels:
  desc: null
  value: /workspace/jordan/Span-Selection/download//conll/labels.txt
max_seq_length:
  desc: null
  value: 128
do_lower_case:
  desc: null
  value: false
eval_test_set:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
eval_batch_size:
  desc: null
  value: 32
gradient_accumulation_steps:
  desc: null
  value: 1
mlp_hidden_size:
  desc: null
  value: 256
mlp_dropout_rate:
  desc: null
  value: 0.2
learning_rate:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 40.0
save_steps:
  desc: null
  value: 200
warmup_steps:
  desc: null
  value: 800
overwrite_output_dir:
  desc: null
  value: true
seed:
  desc: null
  value: 4
neg_sample_rate:
  desc: null
  value: 0.35
select_begin_epoch:
  desc: null
  value: 1
pbegin_f1:
  desc: null
  value: 0.6
select_positive:
  desc: null
  value: true
select_negative:
  desc: null
  value: true
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685359266.344593
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      6: 4.29.1
      8:
      - 5
    m:
    - 1: f1-dev
      6:
      - 3
      7:
      - 2
    - 1: f1-test
      6:
      - 3
      7:
      - 2
